giantswarm/organization-operator

go.mod, service/controller/resource/organization/create.go, service/controller/resource/organization/delete.go, service/controller/resource/organization/resource.go
Towards https://github.com/giantswarm/roadmap/issues/148
=> Reconciliation loop

CHANGELOG.md, pkg/project/project.go
=> Prepare release v0.1.0

pkg/project/project.go
=> Bump version to 0.1.0-dev

.github/dependabot.yml, .github/workflows/zz_generated.gomodtidy.yaml, CHANGELOG.md
=> Add Dependabot

.github/workflows/zz_generated.create_release.yaml, .github/workflows/zz_generated.create_release_pr.yaml
=> add workflows

.github/dependabot.yml
=> Bump k8s version in dependabot config

CHANGELOG.md, helm/organization-operator/templates/service.yaml
=> Add monitoring label

helm/organization-operator/Chart.yaml
Towards giantswarm/giantswarm#14846
=> Add team annotation to Chart.yaml

.circleci/config.yml
=> push to shared app collection

go.mod, go.sum
=> Update protobuf dependency

service/controller/resource/organization/delete.go
No need to update the changelog
=> Add comment regarding org deletion and credentials

CHANGELOG.md, helm/organization-operator/Chart.yaml, helm/organization-operator/templates/deployment.yaml, helm/organization-operator/values.yaml
=> Set config version

.circleci/config.yml, CHANGELOG.md
=> Update arhitect-orb to v3.0.0

helm/organization-operator/Chart.yaml
Towards https://github.com/giantswarm/giantswarm/issues/19760
=> Set team annotation in Chart.yaml for app alert routing

CHANGELOG.md, service/controller/resource/organization/delete.go
Fixes https://github.com/giantswarm/giantswarm/issues/20319
=> don't return error if legacy org deletion fails

CHANGELOG.md, helm/organization-operator/Chart.yaml, helm/organization-operator/templates/pull-secret.yaml, helm/organization-operator/values.yaml
The deployment for this operator references a non-existent secret. This adds the secret.
=> Add image pull-secret referenced by deployment

.circleci/config.yml, CHANGELOG.md
=> Remove shared app collection

.circleci/config.yml
Towards https://github.com/giantswarm/roadmap/issues/2235
=> push organization operator to all app collections

pkg/project/project.go
=> Bump version to 1.0.8-dev

CHANGELOG.md, helm/organization-operator/Chart.yaml, helm/organization-operator/templates/_helpers.tpl, helm/organization-operator/templates/deployment.yaml, helm/organization-operator/templates/service.yaml, helm/organization-operator/templates/servicemonitor.yaml, helm/organization-operator/values.schema.json, helm/organization-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/27145
=> Add Service Monitor

CHANGELOG.md, helm/organization-operator/templates/psp.yaml, helm/organization-operator/values.schema.json, helm/organization-operator/values.yaml
Towards https://github.com/giantswarm/giantswarm/issues/28338
=> PSP Toggle

CHANGELOG.md, flag/service/service.go, helm/organization-operator/templates/configmap.yaml, helm/organization-operator/values.yaml, main.go, service/controller/org.go, service/service.go
Adds a new config var to set the duration of the reconcile loop in operatorkit.
=> Add config var for resync period

CHANGELOG.md, helm/organization-operator/templates/rbac.yaml, service/controller/resource/organization/create.go
Towards https://github.com/giantswarm/giantswarm/issues/30000
=> ensure org namespace is patched with org labels

.circleci/config.yml, .nancy-ignore, CHANGELOG.md
Towards https://github.com/giantswarm/giantswarm/issues/31374
=> Bump architect-orb@5.3.1

CHANGELOG.md, internal/controller/organization_controller.go, internal/controller/organization_controller_test.go
This PR:
- implements fixes on `organization/namespace` deletion
=> Fix organization deletion/namespace

CHANGELOG.md, internal/controller/organization_controller.go, internal/controller/organization_controller_test.go
- Added  handling on deletion for the old finalizer.
=> old organization handling

.golangci.yml, CHANGELOG.md, internal/controller/organization_controller.go, internal/controller/organization_controller_test.go, main.go
=> Resolve golangci v2 linter problems
